spring:
  application:
    name: music-stream-api

  datasource:
    url: jdbc:postgresql://localhost:5433/musicstream
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  jackson:
    serialization:
      write-dates-as-timestamps: false


  jpa.open-in-view: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


file:
  upload-dir: ./uploads
  max-audio-size: 52428800
  max-image-size: 20971520

logging:
  level:
    com.musicstream: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG